dist: xenial
language: node_js
node_js: "10"

cache: 
  - pip
  - npm

matrix:
  fast_finish: true
  include:
    - python: "3.7"
      language: python
      cache: pip

    - cache: pip
      os: osx
      osx_image: xcode11.2

addons:
  homebrew:
    update: true
    packages:
      - python

before_install:
  - nvm install 10.13.0 && nvm use 10.13.0

install:
    - python3 -m pip install -e .[dev]
    - python3 -m pip install -U codecov pandas cufflinks
    - yarn

script: 
  - make test
  - make extest
  - make exlint

after_success:
    - codecov --token d27a997e-fcb8-4d29-986e-e87118f046f5

branches:
  only:
  - master

notifications:
  email: false
