language: python
cache: 
  - pip
  - npm

python:
  - "3.6"

install:
    - pip install -r requirements.txt
    # pandas and cufflinks could be added as test dependencies in setup.py
    - pip install -U codecov pandas cufflinks
    - yarn

script: 
  - make test
  - make extest
  - make exlint

after_success:
    - codecov --token d27a997e-fcb8-4d29-986e-e87118f046f5

branches:
  only:
  - master

notifications:
  email: false
