dist: xenial

cache: 
  - pip
  - npm

matrix:
  fast_finish: true
  include:
    - python: "3.7"
      language: python
      cache: pip

    - cache: pip
      os: osx
      osx_image: xcode11.2

addons:
  homebrew:
    update: true
    packages:
      - python

install:
    - pip install -e .[dev]
    # pandas and cufflinks could be added as test dependencies in setup.py
    - pip install -U codecov pandas cufflinks
    - yarn

script: 
  - make test
  - make extest
  - make exlint

after_success:
    - codecov --token d27a997e-fcb8-4d29-986e-e87118f046f5

branches:
  only:
  - master

notifications:
  email: false
