trigger:
  branches:
    include:
      - master
  tags:
    include:
      # todo: should we just include all tags? (see conditional package upload step)
      - v0.*

jobs:
- template: .azure/default-job.yml
  parameters:
    name: 'Linux'
    pool:
      vmImage: 'ubuntu-latest'

    - script: |
        # duplicates pyproject.toml; see https://github.com/pypa/pip/issues/6041 etc etc etc...
        python -m pip install wheel setuptools jupyter-packaging twine
        make dist
      displayName: 'Create packages'

    - task: TwineAuthenticate@0
      inputs:
        artifactFeeds: jupyter/python-packages

    - script: |
        twine check dist/* && twine upload -r jupyter/python-packages --config-file $(PYPIRC_PATH) dist/*
      displayName: 'Upload packages'
      condition: contains(variables['Build.SourceBranch'], 'tags')  # todo: match "release" style tags only (v...)

    - task: Npm@1
      inputs:
        command: publish
        publishRegistry: useFeed
        publishFeed: jupyter/python-packages
      condition: contains(variables['Build.SourceBranch'], 'tags')  # todo: match "release" style tags only (v...)


- template: .azure/default-job.yml
  parameters:
    name: 'Mac'
    pool:
      vmImage: 'macos-10.14'


- template: .azure/default-job.yml
  parameters:
    name: 'Windows'
    pool:
      vmImage: 'vs2017-win2016'
