parameters:
  name: ''
  pool: ''
  also_forked: true

jobs:
- job: ${{ parameters.name }}
  pool: ${{ parameters.pool }}

  strategy:
    matrix:
      Python27:
        python.version: '2.7'
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
      Python38:
        python.version: '3.8'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
    displayName: 'Use Python $(python.version)'

  - task: NodeTool@0
    inputs:
      versionSpec: '12.x'

  - bash: npm install -g yarn
    displayName: "Install Yarn"

  - bash: cd js; yarn
    displayName: "Install JS dependencies"

  - script: |
      python -m pip install --upgrade pip
      pip install -e .[dev]
      jupyter labextension install js
      jupyter serverextension enable --py nbcelltests
    displayName: 'Developer install'

  - script:
      make verify-install
    displayName: 'Check everything was installed'

  - script: |
      make lint
    displayName: 'Lint'

  - ${{ if eq(parameters.also_forked, 'true') }}:

    - script:
        make testpy-forked
      displayName: 'pytest --forked'

  - script:
      make tests
    displayName: 'Test'

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFiles: 'python_junit.xml'
      testRunTitle: 'Publish test results for Python $(python.version) $(manylinux_flag)'

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/*coverage.xml'
