trigger:
  branches:
    include:
      - master
  tags:
    include:
      # todo: should we just include all tags? (see conditional package upload step)
      - v0.*

jobs:
- template: .azure/default-job.yml
  parameters:
    name: 'Linux'
    pool:
      vmImage: 'ubuntu-latest'
    packages: true

- template: .azure/default-job.yml
  parameters:
    name: 'Mac'
    pool:
      vmImage: 'macos-10.14'

- template: .azure/default-job.yml
  parameters:
    name: 'Windows'
    pool:
      vmImage: 'vs2017-win2016'
