parameters:
  name: ''
  pool: ''

jobs:
- job: ${{ parameters.name }}
  pool: ${{ parameters.pool }}

  strategy:
    matrix:
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
      Python38:
        python.version: '3.8'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
    displayName: 'Use Python $(python.version)'

  - task: NodeTool@0
    inputs:
      versionSpec: '12.x'

  # TODO: would prefer to specify version of celltests instead of using --pre
  # TODO: change to some temp dir
  - script: |
      python -m pip install --upgrade pip
      pip install --pre --index-url=https://pkgs.dev.azure.com/tpaine154/jupyter/_packaging/packages-testing/pypi/simple/ nbcelltests --extra-index-url=https://pypi.org/simple
      jupyter lab build
    displayName: 'User install'

  # TODO: this is make verify-install, but can't run that on win (unless we install make...)
  - script: |
      jupyter labextension check jupyterlab_celltests
      python -c "import subprocess,re,sys; import nbcelltests;  ext=subprocess.check_output(['jupyter','serverextension','list'],stderr=subprocess.STDOUT).decode();  print(ext);  res0=re.search('.*nbcelltests.*{}.*ok'.format(nbcelltests.__version__),ext,re.IGNORECASE);  res1=re.search('nbcelltests.*enabled', ext);  sys.exit(not (res0 and res1))"
    displayName: 'Check everything was installed'
